(* Simulate the script loading environment. *)

include Lib
include Fusion
include Basics
include Nets
include Printer
include Preterm
include Parser
include Equal
include Boolean
include Drule
include Tactics
include Itab
include Simp
include Theorems
include Ind_defs
include Class
include Trivia
include Canon
include Meson
include Firstorder
include Metis
include Thecops
include Quot
include Impconv
include Pair
include Compute
include Nums
include Recursion
include Arith
include Wf
include Calc_num
include Normalizer
include Grobner
include Ind_types
include Lists
include Realax
include Calc_int
include Realarith
include Real
include Calc_rat
include Int
include Sets
include Iterate
include Cart
include Define
include Help
include Database

let all_loaded = true
